[package]
name = "amplifier_lints"
version = "0.1.0"
authors = ["authors go here"]
description = "description goes here"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
warn_on_unwraps = { path = "warn_on_unwraps", features = ["rlib"] }
ensure_msg_has_permissions = { path = "ensure_msg_has_permissions", features = ["rlib"] }
restrict_cosmwasm_addr_in_msg_struct = { path = "restrict_cosmwasm_addr_in_msg_struct", features = ["rlib"] }

dylint_linting = { workspace = true }

[dev-dependencies]
dylint_testing = { workspace = true }

[package.metadata.rust-analyzer]
rustc_private = true
