# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml
name: Basic

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Suite
    runs-on: blacksmith-32vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-04-03
          components: rustc-dev, llvm-tools-preview
          override: true

      - name: Install cargo-dylint
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-dylint

      - name: Install dylint-link
        uses: baptiste0928/cargo-install@v2
        with:
          crate: dylint-link

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache build artifacts
        uses: useblacksmith/rust-cache@v3.0.1
        id: cache
        with:
          shared-key: "cache-tests"

      - name: Log crates.toml
        if: steps.cache.outputs.cache-hit == 'true'
        run: cat /home/runner/.cargo/.crates.toml

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --no-fail-fast
        env:
          RUSTFLAGS: --cfg tracing_unstable
          RUST_BACKTRACE: 1

  lints:
    name: Lints
    runs-on: blacksmith-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache build artifacts
        uses: useblacksmith/rust-cache@v3.0.1
        id: cache
        with:
          shared-key: "cache-lints"

      - name: Log crates.toml
        if: steps.cache.outputs.cache-hit == 'true'
        run: cat /home/runner/.cargo/.crates.toml

      - name: Install cargo-sort
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-sort

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-04-03
          components: rustc-dev, llvm-tools-preview, clippy
          override: true

      - name: Run cargo sort
        uses: actions-rs/cargo@v1
        with:
          command: sort
          args: --workspace --check --check-format

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings -A deprecated

      - name: Check Diff
        # fails if any changes not committed
        run: git diff --exit-code
